### ISSUE TITLE
QR Code Generator

### ISSUE THREAD

**Issue by sumana2001** [sumana2001/python#13]
Write a script to generate QR code in python

**Comment by tht-jxny** [comment]
I could do this with a qr-code library. Do you want to assign it to me?

**Comment by aa-ryan** [comment]
I can do that with Pyqrcode, tkinter, PIL, the project will be GUI based with a good Readme, so that it is easy for beginners to use. (I am also a Beginner though).
Do you want to assign it to me?

**Comment by GSantos23** [comment]
Hi, Do we need to use an special library or is free to decide which to use? I would like to work in this one.

Could you assign it to me?

**Comment by sumana2001** [comment]
Go ahead! 

Make a proper readme, include dependencies and screenshots. If anything else needs to be changed do mention that.

**Comment by aa-ryan** [comment]
#19 PR Addresses this Issue
Includes Documentation, installation requirements and ScreenShots
