### ISSUE TITLE
Music Recommendation System

### ISSUE THREAD

**Issue by sumana2001** [sumana2001/python#14]
Recommends music according to genre preferred by the user

**Comment by dulangaheshan** [comment]
is it to be a supervised machine learning approach? if is it then is there any data set related to it

**Comment by sumana2001** [comment]
@dulangaheshan yes supervised ml approach. Add any sample data set from your end for me the code is important rather than data 

Happy coding! 😁

**Comment by dulangaheshan** [comment]
@sumana2001 what are the criteria for identifying the preferred genre by the user (no of paly times, users rate. etc), and if there is not sufficient data for train the model then what to do

**Comment by sumana2001** [comment]
@dulangaheshan  You might be very familiar with a music recommendation system if you’ve used apps like JioSaavn or Spotify. The system recommends some songs based on the songs you’ve liked or listened to. How does the system do this? This is a typical example where Machine Learning can be applied. This can further be extended for recommendation system which many E-Commerce sites use to suggest some other products which you like to buy with the current one or can be extended for the recommendation system in apps like Netflix or Amazon Prime.

I am not aiming at accuracy you do with some small datasets. If you want more data you can go to [Kaggle](https://www.kaggle.com/) and find some relevant datasets.

Hope you enjoy making it😁

**Comment by dulangaheshan** [comment]
yeah got it, assign to me this task

**Comment by dulangaheshan** [comment]
I'm going to implement a collaborative filtering approach for recommendation can you please open an another issue

**Comment by Aniket762** [comment]
Hey @dulangaheshan sorry for late reply was stuck with exams. It will be great if you create the issue and create the pull request, Once you create the issue I will assign it to you!
