### ISSUE TITLE
Voice Interpreter

### ISSUE THREAD

**Issue by sumana2001** [sumana2001/python#17]
Voice assistant which listens to you, opens websites, plays music, replies back to you etc.

**Comment by Vineet-Dhaimodker** [comment]
Please assign this issue to me @sumana2001. I would love to contribute.

**Comment by sumana2001** [comment]
@Vineet-Dhaimodker  Go ahead with it!😁

Don't forget to add screenshots, list of dependencies and proper readme

**Comment by Vineet-Dhaimodker** [comment]
Yes sure. Thanks for assigning. Could you please assign me the binary search issue also @sumana2001.
