### ISSUE TITLE
Loan Prediction using Machine Learning

### ISSUE THREAD

**Issue by sumana2001** [sumana2001/python#24]
Loan Prediction using Machine Learning
Project idea – The idea behind this ML project is to build a model that will classify how much loan the user can take. It is based on the user’s marital status, education, number of dependents, and employments. We can build a linear model for this project.

https://www.kaggle.com/altruistdelhite04/loan-prediction-problem-dataset

**Comment by vaderjunior** [comment]
Hey,
I would like to work on this

**Comment by Aniket762** [comment]
@vaderjunior Go ahead !

Happy Coding 😁

**Comment by vaderjunior** [comment]
Hey @Aniket762 Ive done a PR, Please look into it
Thanks
