### ISSUE TITLE
Guess the number

### ISSUE THREAD

**Issue by sumana2001** [sumana2001/python#25]
Write a program where the computer randomly generates a number between 0 and 20. The user needs to guess what the number is. If the user guesses wrong, tell them their guess is either too high, or too low. This will get you started with the random library if you haven't already used it.

**Will only assign to a github beginner**

**Comment by meghanagottapu** [comment]
can I take up this issue? @sumana2001

**Comment by sumana2001** [comment]
Hey @meghanagottapu,  I want to assign this issue to a beginner. I want beginners to learn about pull requests and contributing to other's repo. You can checkout other issues or make your own issue and contribute.

Happy Coding 😁

**Comment by Shrey2002** [comment]
> Hey @meghanagottapu, I want to assign this issue to a beginner. I want beginners to learn about pull requests and contributing to other's repo. You can checkout other issues or make your own issue and contribute.
> 
> Happy Coding 😁

can I work on this I am new to github!! please assign this to me..

**Comment by sumana2001** [comment]
Hey @Shrey2002 , good luck mate!

Happy coding 😁

**Comment by Shrey2002** [comment]
thank u!

**Comment by Shrey2002** [comment]
> Hey @Shrey2002 , good luck mate!
> 
> Happy coding 😁

I have done the coding #30
