### ISSUE TITLE
Rock Paper Scissor 

### ISSUE THREAD

**Issue by sumana2001** [sumana2001/python#27]
The game is self explanatory. The game must have a nice GUI.

**Comment by shrey27tri01** [comment]
Can I work on this issue?
Also, can you please elaborate on the "GUI" part? As in, do we have to implement this using Pygame, or on the command line?

**Comment by sumana2001** [comment]
Hey, @shrey27tri01 ! You need to implement using Pygame

**Comment by shrey27tri01** [comment]
@sumana2001 Thank you! I will start working on this. Will raise a PR soon :)
