### ISSUE TITLE
Convert png to jpg 

### ISSUE THREAD

**Issue by sumana2001** [sumana2001/python#33]
Use python script to code it.

**Comment by ahthserhsluk** [comment]
i can do it. please assign it to me.
thank you:)

**Comment by sumana2001** [comment]
Go ahead 😁

**Comment by ahthserhsluk** [comment]
just one thing you want it to be an app-based or just the program?

**Comment by Aniket762** [comment]
App-based

**Comment by shairanshrawat** [comment]
I can work on this
