### ISSUE TITLE
Youtube video downloader

### ISSUE THREAD

**Issue by sumana2001** [sumana2001/python#35]
Make a GUI for downloading videos from Youtube.

**Comment by aa-ryan** [comment]
I would love to contribute to this project.

**Comment by sumana2001** [comment]
@Aryan-dev007  Go ahead 😁

Please add proper readme, dependencies and screenshots

**Comment by aa-ryan** [comment]
Please check #19 I have already added this.
Consider merging it!
Thanks!

**Comment by aa-ryan** [comment]
@sumana2001 @Aniket762 Please Close this issue since it is already resolved.
